
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 16 22:41:24 CDT 2023
//----------------------------------------------------

package ejcompilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_DESCRIBE = 27;
  public static final int IDENTIFICADOR = 113;
  public static final int PR_FOR = 75;
  public static final int PR_TO = 25;
  public static final int PR_ADD = 49;
  public static final int PR_SAVEPOINT = 83;
  public static final int PR_CHANGE = 47;
  public static final int PR_FOREIGN = 52;
  public static final int PR_INT = 8;
  public static final int PR_PRIMARY = 51;
  public static final int PR_AS = 60;
  public static final int PR_CHAR = 14;
  public static final int PR_GRANT = 77;
  public static final int PR_WHERE = 34;
  public static final int LIKE = 98;
  public static final int PR_DATABASES = 3;
  public static final int PR_ELSE = 73;
  public static final int PUNTOYC = 84;
  public static final int PR_GROUP_BY = 36;
  public static final int PR_SHOW = 26;
  public static final int PR_FUNCTION = 68;
  public static final int PR_NULL = 58;
  public static final int PR_SET = 30;
  public static final int PR_CONSTRAINT = 63;
  public static final int PR_FO_JOIN = 46;
  public static final int PR_DELETE = 33;
  public static final int NOT = 101;
  public static final int PR_SELECT = 28;
  public static final int PR_END = 71;
  public static final int PR_PROCEDURE = 67;
  public static final int S_MODULO = 107;
  public static final int PR_CHECK = 55;
  public static final int ERROR = 114;
  public static final int FLOAT = 112;
  public static final int PR_ORDER_BY = 35;
  public static final int PR_DATE = 17;
  public static final int PR_REFERENCES = 61;
  public static final int LLAVE_C = 89;
  public static final int PR_BEGIN = 70;
  public static final int PR_DATABASE = 5;
  public static final int PR_LIMIT = 41;
  public static final int PR_TRUNCATE = 23;
  public static final int PR_DESC = 103;
  public static final int LLAVE_A = 88;
  public static final int PR_TABLES = 2;
  public static final int S_DIV = 106;
  public static final int PR_DISTINCT = 39;
  public static final int PR_DECLARE = 69;
  public static final int COMA = 85;
  public static final int PR_KEY = 7;
  public static final int IGUAL = 90;
  public static final int P_OPEN = 86;
  public static final int PR_I_JOIN = 43;
  public static final int PR_DROP = 21;
  public static final int PR_OFFSET = 42;
  public static final int PR_USER = 79;
  public static final int P_CLOSE = 87;
  public static final int CADENA_CARACT = 110;
  public static final int S_MULT = 108;
  public static final int PR_CREATE = 20;
  public static final int PR_TABLE = 4;
  public static final int INT = 111;
  public static final int PR_UNIQUE = 54;
  public static final int PR_ASC = 102;
  public static final int PR_FROM = 29;
  public static final int PR_TIME = 18;
  public static final int BETWEEN = 97;
  public static final int MENORIG = 95;
  public static final int EOF = 0;
  public static final int PUNTO = 109;
  public static final int PR_ROLLBACK = 82;
  public static final int PR_NOT_NULL = 57;
  public static final int PR_PASSWORD = 80;
  public static final int S_SUMA = 104;
  public static final int PR_DECIMAL = 12;
  public static final int PR_COMMIT = 81;
  public static final int PR_VALUES = 66;
  public static final int PR_HAVING = 40;
  public static final int IN = 96;
  public static final int PR_ENUM = 16;
  public static final int OR = 100;
  public static final int error = 1;
  public static final int PR_UPDATE = 32;
  public static final int PR_RENAME = 24;
  public static final int PR_AUTO_INCREMENT = 59;
  public static final int PR_INSERT = 31;
  public static final int PR_JOIN = 37;
  public static final int S_RESTA = 105;
  public static final int PR_COLUMN = 48;
  public static final int MENORQ = 93;
  public static final int PR_DATETIME = 19;
  public static final int PR_FLOAT = 10;
  public static final int PR_BIGINT = 9;
  public static final int PR_DEFAULT = 56;
  public static final int MAYORQ = 92;
  public static final int PR_LOOP = 76;
  public static final int PR_ON = 50;
  public static final int PR_REVOKE = 78;
  public static final int PR_IF = 72;
  public static final int PR_REPLACE = 62;
  public static final int NOIGUAL = 91;
  public static final int PR_VIEW = 6;
  public static final int PR_STORED = 64;
  public static final int PR_TEXT = 15;
  public static final int PR_VARCHAR = 13;
  public static final int PR_R_JOIN = 45;
  public static final int AND = 99;
  public static final int MAYORIG = 94;
  public static final int PR_ALTER = 22;
  public static final int PR_INDEX = 53;
  public static final int PR_L_JOIN = 44;
  public static final int PR_WHILE = 74;
  public static final int PR_UNION = 38;
  public static final int PR_DOUBLE = 11;
  public static final int PR_INTO = 65;
}

